# Generated by Django 5.2.7 on 2025-10-17 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingest', '0005_ingestmarket_source_price_ingestmarket_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastModelEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('multi_r', models.FloatField()),
                ('heavy_r2', models.FloatField()),
                ('adjusted_r2', models.FloatField()),
                ('sign_f', models.FloatField()),
                ('standard_error', models.FloatField()),
                ('rmse', models.FloatField()),
                ('reg_variation', models.FloatField()),
                ('reg_variance', models.FloatField()),
                ('res_variation', models.FloatField()),
                ('res_variance', models.FloatField()),
                ('total_variation', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForecastModelVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('previous_term', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ForecastModelKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag_name', models.CharField(max_length=100, unique=True)),
                ('vegetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_model_kinds', to='ingest.vegetable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForecastModelFeatureSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_month', models.IntegerField()),
                ('model_kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_model_feature_sets', to='forecast.forecastmodelkind')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_model_feature_sets', to='forecast.forecastmodelvariable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForecastModelCoef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_segment', models.BooleanField(default=False)),
                ('coef', models.FloatField()),
                ('value_t', models.FloatField()),
                ('sign_p', models.FloatField()),
                ('standard_error', models.FloatField()),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_model_coefs', to='forecast.forecastmodelvariable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForecastModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_month', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('model_kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_model_versions', to='forecast.forecastmodelkind')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
