# Generated by Django 5.2.7 on 2025-10-31 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_forecastmodelevaluation_model_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastmodelcoef',
            name='model_version',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coefficients', to='forecast.forecastmodelversion'),
        ),
    ]
