# Generated by Django 5.2.7 on 2025-10-16 01:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingest', '0005_ingestmarket_source_price_ingestmarket_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputeMarket',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_year', models.IntegerField()),
                ('target_month', models.IntegerField()),
                ('target_half', models.CharField(max_length=5)),
                ('average_price', models.FloatField(blank=True, null=True)),
                ('source_price', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('trend', models.CharField(blank=True, max_length=10, null=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compute_markets', to='ingest.region')),
                ('vegetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compute_markets', to='ingest.vegetable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComputeWeather',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_year', models.IntegerField()),
                ('target_month', models.IntegerField()),
                ('target_half', models.CharField(max_length=5)),
                ('max_temp', models.FloatField(blank=True, null=True)),
                ('mean_temp', models.FloatField(blank=True, null=True)),
                ('min_temp', models.FloatField(blank=True, null=True)),
                ('sum_precipitation', models.FloatField(blank=True, null=True)),
                ('sunshine_duration', models.FloatField(blank=True, null=True)),
                ('ave_humidity', models.FloatField(blank=True, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compute_weathers', to='ingest.region')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
