# Generated by Django 5.2.8 on 2025-11-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computemarket',
            name='prev_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computemarket',
            name='prev_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computemarket',
            name='years_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computemarket',
            name='years_volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
