# Generated by Django 5.2.7 on 2025-10-29 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObserveReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_year', models.IntegerField()),
                ('target_month', models.IntegerField()),
                ('target_half', models.CharField(max_length=5)),
                ('predict_price', models.FloatField()),
                ('min_price', models.FloatField()),
                ('max_price', models.FloatField()),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observe_reports', to='forecast.forecastmodelversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ObserveResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_date', models.DateField()),
                ('is_corrected', models.BooleanField(default=False)),
                ('diff', models.FloatField()),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observe_results', to='forecast.forecastmodelversion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
