"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xa7o_f7r7bd@0+e%z)ls+hhxm(0g+j!raa=2#4i(#c@*0zqh5^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# データ関連のパス設定
INGEST_ROOT = os.getenv("INGEST_ROOT", "/data")
# 新しいディレクトリ構造
INGEST_PREFIX_PRICE = os.getenv("INGEST_PREFIX_PRICE", "price/")
INGEST_PREFIX_WEATHER = os.getenv("INGEST_PREFIX_WEATHER", "weather/")

# ベースとなるディレクトリ
DATA_BASE_DIR = os.path.join(BASE_DIR.parent.parent, "data")

# Azuriteを無効にするフラグ（マイグレーション専用）
AZURE_DISABLE = os.environ.get('AZURE_DISABLE', 'False').lower() == 'true'

# Azure Storage settings
AZURE_ACCOUNT_NAME = os.getenv("AZURE_ACCOUNT_NAME", "devstoreaccount1")
AZURE_CONTAINER = os.getenv("AZURE_STORAGE_CONTAINER", "container")

if AZURE_DISABLE:
    # Azuriteが無効の場合はダミー値を設定
    AZURE_CONNECTION_STRING = "DefaultEndpointsProtocol=http;AccountName=dummy;AccountKey=dummy;BlobEndpoint=http://localhost:10000/devstoreaccount1;"
    DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
else:
    # 通常の設定
    AZURE_CONNECTION_STRING = os.getenv("AZURE_CONNECTION_STRING", "")
    DEFAULT_FILE_STORAGE = "storages.backends.azure_storage.AzureStorage"
    
AZURE_ACCOUNT_KEY = os.getenv("AZURE_ACCOUNT_KEY", "")  # conn strを優先するので空でもOK
AZURE_SSL = False  # Azuriteはhttpで十分（httpsにすると繋がらないことが多い）
AZURE_URL_EXPIRATION_SECS = 3600  # 署名URL有効時間（必要に応じて）
AZURE_OVERWRITE_FILES = False


ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "storages",

    'accounts.apps.AccountsConfig',
    'ingest.apps.IngestConfig',
    'compute.apps.ComputeConfig',
    'feedback.apps.FeedbackConfig',
    'reports.apps.ReportsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'config', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB'),
        'USER': os.getenv('POSTGRES_USER'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
        'HOST': os.getenv('POSTGRES_HOST'),
        'PORT': os.getenv('POSTGRES_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # 'static'から'staticfiles'に変更
STATICFILES_DIRS = []

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 認証関連の設定
LOGIN_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/admin/'
