# Generated by Django 5.2.7 on 2025-10-31 08:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vegetable', models.CharField(max_length=50, verbose_name='野菜')),
                ('month', models.IntegerField(verbose_name='月')),
                ('status', models.CharField(max_length=20, verbose_name='ステータス')),
                ('description', models.TextField(verbose_name='説明')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'モデル評価',
                'verbose_name_plural': 'モデル評価',
                'indexes': [models.Index(fields=['vegetable', 'month'], name='feedback_mo_vegetab_370270_idx'), models.Index(fields=['created_at'], name='feedback_mo_created_02fdb9_idx')],
                'unique_together': {('vegetable', 'month', 'created_at')},
            },
        ),
        migrations.CreateModel(
            name='PredictionMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vegetable', models.CharField(max_length=50, verbose_name='野菜')),
                ('month', models.IntegerField(verbose_name='月')),
                ('r2_score', models.FloatField(verbose_name='決定係数')),
                ('std_error', models.FloatField(verbose_name='標準誤差')),
                ('mae', models.FloatField(verbose_name='平均絶対誤差')),
                ('rmse', models.FloatField(verbose_name='二乗平均平方根誤差')),
                ('f_significance', models.FloatField(verbose_name='F値の有意確率')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '予測精度メトリクス',
                'verbose_name_plural': '予測精度メトリクス',
                'indexes': [models.Index(fields=['vegetable', 'month'], name='feedback_pr_vegetab_f4c4aa_idx'), models.Index(fields=['created_at'], name='feedback_pr_created_79ab4a_idx')],
                'unique_together': {('vegetable', 'month', 'created_at')},
            },
        ),
        migrations.CreateModel(
            name='VariableImportance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vegetable', models.CharField(max_length=50, verbose_name='野菜')),
                ('month', models.IntegerField(verbose_name='月')),
                ('variable_name', models.CharField(max_length=100, verbose_name='変数名')),
                ('coefficient', models.FloatField(verbose_name='係数')),
                ('t_value', models.FloatField(verbose_name='t値')),
                ('p_value', models.FloatField(verbose_name='p値')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '変数重要度',
                'verbose_name_plural': '変数重要度',
                'indexes': [models.Index(fields=['vegetable', 'month'], name='feedback_va_vegetab_212fe3_idx'), models.Index(fields=['created_at'], name='feedback_va_created_8d5441_idx')],
                'unique_together': {('vegetable', 'month', 'variable_name', 'created_at')},
            },
        ),
    ]
