# Generated by Django 5.2.6 on 2025-09-20 08:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price_code', models.IntegerField(default=0)),
                ('weather_code', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IngestWeather',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_date', models.DateField()),
                ('max_temp', models.FloatField(blank=True, null=True)),
                ('mean_temp', models.FloatField(blank=True, null=True)),
                ('min_temp', models.FloatField(blank=True, null=True)),
                ('sum_precipitation', models.FloatField(blank=True, null=True)),
                ('sunshine_duration', models.FloatField(blank=True, null=True)),
                ('ave_humidity', models.FloatField(blank=True, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingest_weathers', to='ingest.region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IngestMarket',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_date', models.DateField()),
                ('high_price', models.FloatField(blank=True, null=True)),
                ('medium_price', models.FloatField(blank=True, null=True)),
                ('low_price', models.FloatField(blank=True, null=True)),
                ('average_price', models.FloatField(blank=True, null=True)),
                ('arrival_amount', models.FloatField(blank=True, null=True)),
                ('weight_per', models.FloatField(blank=True, null=True)),
                ('vegetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingest_markets', to='ingest.vegetable')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
