# Generated by Django 5.2.7 on 2025-10-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestmarket',
            name='trend',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
