# Generated by Django 5.2.7 on 2025-10-10 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0002_ingestmarket_trend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='price_code',
            new_name='fuken_code',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='weather_code',
            new_name='market_code',
        ),
        migrations.AddField(
            model_name='ingestmarket',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingest_markets', to='ingest.region'),
        ),
        migrations.AddField(
            model_name='region',
            name='p_area_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='region',
            name='station_code',
            field=models.IntegerField(default=0),
        ),
    ]
