# Generated by Django 5.2.7 on 2025-10-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0003_rename_price_code_region_fuken_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='fuken_code',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='region',
            name='market_code',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='region',
            name='p_area_code',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='region',
            name='station_code',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='vegetable',
            name='code',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
