# Generated by Django 5.2.7 on 2025-10-15 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0004_alter_region_fuken_code_alter_region_market_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestmarket',
            name='source_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingestmarket',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
